language: java

install: true

matrix:
  include:
  - jdk: oraclejdk8

script:
- gradle clean build

before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-v0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://$GITPERM@github.com/RlonRyan/JBasicX_TestingApp --tags
- ls -R

deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITPERM
  file:
  - README.md
  - build/libs/JBasicX-TestingApp-0.1.0.zip
  on:
    tags: false
    all_branches: true

branches:
  except:
  - /^*-v[0-9]/

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
    - irc.esper.net#RlonRyan
    on_success: always
    on_failure: always

env:
  global:
  - secure: lFkTbqcEb8qphbMzp2/cXChw12m8R9/e+2Ht/dFyN90wp+j6qP8hIRoGbV9cK8vxREQk6fwyB1hkYSr3ZfQkhbBmu5nRZzpp+duHlYM6XVlk4mF01g1wkjTgFOVRLLPegir/y5eGNtdll9VrXfUOVMORugXb7FXTeRAMKBGv6QA=
